#!/usr/bin/env python3
"""Embed local HUD/gallery PNGs as data URIs for Twine Test/Play portability."""

from __future__ import annotations

import base64
import mimetypes
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets" / "images"
OUT = ROOT / "source" / "embedded-images.js"

EMBED_PATHS = [
    "assets/images/days-clock.png",
    "assets/images/career-chancellor.png",
    "assets/images/integrity-tower.png",
    "assets/images/wellness-vumc.png",
    "assets/images/student-alex-hormozi.png",
    "assets/images/vanderbilt-star.png",
    "assets/images/gallery-1.png",
    "assets/images/gallery-2.png",
    "assets/images/gallery-3.png",
]


def main() -> None:
    lines = [
        "/* Generated by scripts/embed-assets.py — do not edit by hand. */",
        "setup.images = setup.images || {};",
    ]
    total = 0
    for rel in EMBED_PATHS:
        path = ROOT / rel
        if not path.exists():
            raise SystemExit(f"Missing asset: {rel}")
        mime = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
        data = base64.b64encode(path.read_bytes()).decode("ascii")
        total += len(data)
        lines.append(f'setup.images[{rel!r}] = "data:{mime};base64,{data}";')
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.name} ({len(EMBED_PATHS)} images, ~{total // 1024} KB base64).")


if __name__ == "__main__":
    main()
