#!/usr/bin/env python3
"""Import Twine Publish-to-File HTML back into story/ and source/ files."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STORY = ROOT / "story"
SOURCE = ROOT / "source"
TOOLS = ROOT / "tools"
TWEEGO = TOOLS / "tweego"

PASSAGE_NAMES = {
    "start", "family", "invitation", "resume", "vault", "choose",
    "careerLaw", "careerFinance", "careerResearch", "submitted", "waiting",
    "interview", "rejection", "offer", "check", "twoOffers", "emergency",
    "betrayal", "graduation", "reflection",
}

PASSAGE_HEADER = re.compile(r"^:: ([^\s{]+)(?:\s+\{([^}]*)\})?\s*$")
EMBED_MARKER = "Generated by scripts/embed-assets.py"


def decompile(html_path: Path) -> str:
    if not TWEEGO.exists():
        raise SystemExit("Tweego not found. Run: python3 scripts/build-story.py")
    tmp = ROOT / ".import-decompiled.twee"
    subprocess.run(
        [str(TWEEGO), "-d", "-o", str(tmp), str(html_path)],
        check=True,
        cwd=ROOT,
    )
    text = tmp.read_text(encoding="utf-8")
    tmp.unlink(missing_ok=True)
    return text


def split_passages(decompiled: str) -> tuple[dict[str, str], dict[str, str]]:
    lines = decompiled.splitlines()
    blocks: dict[str, list[str]] = {}
    current = None
    meta: dict[str, str] = {}

    for line in lines:
        match = PASSAGE_HEADER.match(line)
        if match:
            if current and current in PASSAGE_NAMES:
                blocks[current] = "\n".join(blocks.get(current, [])).strip()
            name = match.group(1)
            current = name
            if name in PASSAGE_NAMES:
                blocks[name] = []
                meta[name] = match.group(2) or ""
            else:
                current = None
            continue
        if current and current in PASSAGE_NAMES:
            blocks.setdefault(current, []).append(line)

    if current and current in PASSAGE_NAMES:
        blocks[current] = "\n".join(blocks.get(current, [])).strip()

    missing = PASSAGE_NAMES - set(blocks)
    if missing:
        raise SystemExit(f"Decompiled HTML missing passages: {sorted(missing)}")
    return blocks, meta


def write_passages_twee(blocks: dict[str, str], meta: dict[str, str]) -> None:
    positions = {
        "start": "100,100", "family": "250,100", "invitation": "400,100", "resume": "550,100",
        "vault": "100,250", "choose": "250,250", "careerLaw": "400,250", "careerFinance": "550,250",
        "careerResearch": "100,400", "submitted": "250,400", "waiting": "400,400", "interview": "550,400",
        "rejection": "100,550", "offer": "250,550", "check": "400,550", "twoOffers": "550,550",
        "emergency": "100,700", "betrayal": "250,700", "graduation": "400,700", "reflection": "550,700",
    }
    order = [
        "start", "family", "invitation", "resume", "vault", "choose", "careerLaw", "careerFinance",
        "careerResearch", "submitted", "waiting", "interview", "rejection", "offer", "check",
        "twoOffers", "emergency", "betrayal", "graduation", "reflection",
    ]
    parts = []
    for name in order:
        pos = meta.get(name) or f'"position":"{positions[name]}","size":"100,100"'
        if pos.startswith("{"):
            pos_json = pos
        else:
            pos_json = "{" + pos + "}"
        parts.append(f":: {name} {pos_json}\n{blocks[name]}\n")
    (STORY / "Passages.twee").write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")


def extract_special(decompiled: str, label: str) -> str | None:
    pattern = rf"^:: {re.escape(label)}(?:\s+\[.*?\])?(?:\s+\{{[^}}]*\}})?\s*$"
    lines = decompiled.splitlines()
    capture = False
    collected: list[str] = []
    for line in lines:
        if re.match(pattern, line):
            capture = True
            continue
        if capture:
            if line.startswith(":: "):
                break
            collected.append(line)
    body = "\n".join(collected).strip()
    return body or None


def write_head_twee(storyinit_body: str) -> None:
    head = (STORY / "Head.twee").read_text(encoding="utf-8")
    pattern = r"(:: StoryInit(?:\s+\{[^}]*\})?\s*\n)([\s\S]*?)(?=\n:: |\Z)"
    if not re.search(pattern, head):
        raise SystemExit("Head.twee missing StoryInit passage")
    updated = re.sub(pattern, r"\1" + storyinit_body.rstrip() + "\n", head, count=1)
    (STORY / "Head.twee").write_text(updated, encoding="utf-8")


def strip_embedded_js(js: str) -> str:
    kept: list[str] = []
    for line in js.splitlines():
        if EMBED_MARKER in line:
            continue
        if line.strip() == "setup.images = setup.images || {};":
            continue
        if line.strip().startswith("setup.images[") and "data:" in line:
            continue
        kept.append(line)
    text = "\n".join(kept).strip()
    return (text + "\n") if text else ""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("html", type=Path, help="HTML file from Twine Publish to File")
    parser.add_argument(
        "--no-styles",
        action="store_true",
        help="Do not overwrite source/stylesheet.css",
    )
    parser.add_argument(
        "--no-script",
        action="store_true",
        help="Do not overwrite source/script.js",
    )
    args = parser.parse_args()
    if not args.html.exists():
        raise SystemExit(f"File not found: {args.html}")

    decompiled = decompile(args.html.resolve())
    blocks, meta = split_passages(decompiled)
    write_passages_twee(blocks, meta)

    storyinit = extract_special(decompiled, "StoryInit")
    if storyinit:
        write_head_twee(storyinit)
        print("Updated story/Head.twee (StoryInit) from published HTML.")

    if not args.no_styles:
        css = extract_special(decompiled, "Story Stylesheet")
        if css:
            (SOURCE / "stylesheet.css").write_text(css + "\n", encoding="utf-8")
            print("Updated source/stylesheet.css from published HTML.")

    if not args.no_script:
        js = extract_special(decompiled, "Story JavaScript")
        if js:
            (SOURCE / "script.js").write_text(strip_embedded_js(js), encoding="utf-8")
            print("Updated source/script.js from published HTML (embedded images stripped; rebuild regenerates them).")

    interface = extract_special(decompiled, "StoryInterface")
    if interface:
        (STORY / "StoryInterface.twee").write_text(":: StoryInterface\n" + interface.rstrip() + "\n", encoding="utf-8")
        print("Updated story/StoryInterface.twee from published HTML.")

    print(f"Imported 20 passages into {STORY / 'Passages.twee'}")
    print("Run: python3 scripts/build-story.py")


if __name__ == "__main__":
    main()
